solartherm-crm with vue.js/routes/web.php
<?php
Auth::routes();

Route::get('/', 'PageController@index');

// Leads
Route::get('/leads', 'LeadController@index');
Route::any('/leads/add', 'LeadController@lead_add');
Route::any('/leads/delete/{lead}', 'LeadController@lead_delete');
Route::any('/leads/assessment', 'LeadController@assessment');
Route::any('/leads/calculator', 'LeadController@calculator');
Route::get('/leads/{lead}', 'LeadController@lead')->middleware('can:access-lead,lead');
Route::post('/leads/{lead}/mark', 'LeadController@mark');
Route::post('/leads/{lead}/allocations', 'LeadController@allocations');
Route::any('/leads/{lead}/assessment', 'LeadController@assessment');
Route::any('/leads/{lead}/saps', 'LeadController@saps');
Route::any('/leads/{lead}/orders', 'LeadController@orders');

// Checks
Route::any('/assessments', 'AssessmentController@index');
Route::any('/assessments/add', 'AssessmentController@add');
Route::any('/assessments/solar-pv/{assessment}', 'AssessmentController@solar_pv');
Route::any('/assessments/hybrid-boiler/{assessment}', 'AssessmentController@hybrid_boiler');

// SAPs
Route::get('/saps', 'SapController@index');
Route::any('/saps/add', 'SapController@add');
Route::any('/saps/{sap}', 'SapController@show');
Route::any('/saps/{sap}/property', 'SapController@property');
Route::any('/saps/{sap}/system', 'SapController@system');
Route::any('/saps/{sap}/cash-flow', 'SapController@cash_flow');
Route::any('/saps/{sap}/summary', 'SapController@summary');
Route::any('/saps/{sap}/cancel/', 'SapController@cancel');

// Orders
Route::get('/orders', 'OrderController@index');
Route::post('/orders/add', 'OrderController@add');
Route::any('/orders/{order}', 'OrderController@show');
Route::get('/orders/{order}/pdf', 'OrderController@pdf');
Route::any('/orders/{order}/finance', 'OrderController@finance');
Route::any('/orders/{order}/confirmation', 'OrderController@confirmation');
Route::post('/orders/{order}/sign', 'OrderController@sign');

// Surveys
Route::get('/surveys', 'SurveyController@index');

// Installs
Route::get('/installations', 'InstallationController@index');

// Users
Route::any('/users', 'UserController@users');
Route::any('/users/add', 'UserController@users_add');
Route::any('/users/roles', 'UserController@roles');
Route::any('/users/teams', 'UserController@teams');
Route::any('/users/{user}', 'UserController@user');

// Other
Route::get('/logs', 'PageController@logs');
Route::get('/links', 'PageController@links');
Route::get('logout', 'Auth\LoginController@logout');
Route::any('/settings', 'PageController@settings');

// New lead
Route::post('/public/add', 'PublicController@add');
Route::post('/public/legacy/add', 'PublicController@legacy_add');

// APIs
Route::any('/api/yield', 'ApiController@array_yield');

solartherm-crm with vue.js/app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = [
        'lead_id',
        'sap_id',

        'appointment_at',
        'deposit',
        'payment_method',

        'finance_completed_at'.

        'customer_signature',
        'customer_signed_at',
        'customer_signed_ip',

        'assessor_signature',
        'assessor_signed_at',
        'assessor_signed_ip',

        'completed_at',
        'signed_at',
        'status',
        'notes',
        'created_at',
        'updated_at'
    ];

    public function lead()
    {
        return $this->belongsTo(Lead::class);
    }

    public function sap()
    {
        return $this->belongsTo(Sap::class);
    }
}

solartherm-crm with vue.js/app/Models/SolarPvSapSystem.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
Use Config;
class SolarPvSapSystem extends Model
{
    protected $fillable = [
        'sap_id',
        'battery',
        'battery_usage',
        'chop_cloc',
        'panels',
        'inverter_type',
        'aframes',
        'voltage_optimiser',
        'solar_usage_percentage',
        'black_framed_panels',
        'government_fit_rate',
        'electricity_export_rate',
        'electricity_rate',
        'system_cost',
        'annual_system_output',
        'monitoring_device',
        'hot_water_controller',
    ];

    protected $casts = [
        'panels' => 'array',
    ];

    public function getProductsAttribute()
    {
        $product_list = [];
        $product_list[] = ["Solar PV Panels", 10];
        $product_list[] = [Config::get('crm.products.solar-pv.inverter_types.'.$this->inverter_type), 1];
        $product_list[] = ["A-frames", $this->aframes];
        if($this->battery =='y') $product_list[] = ["Storage battery", 1];
        if($this->chop_cloc =='y') $product_list[] = ["Chop-Cloc", 1];
        if($this->voltage_optimiser =='y') $product_list[] = ["Voltage optimiser", 1];
        if($this->monitoring_device =='y') $product_list[] = ["Solar monitoring device", 1];
        if($this->hot_water_controller =='y') $product_list[] = ["Hot water controller", 1];

        return $product_list;
    }
    public function getServicesAttribute()
    {
        return Config::get('crm.products.solar-pv.services_included');
    }

}

solartherm-crm with vue.js/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use EntrustUserTrait;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name','last_name', 'team_id', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function team()
    {
        return $this->belongsTo(Team::class);
    }

    public function leads()
    {
        if ($this->hasRole('admin')) {
            return Lead::with('allocations');
        }

        return $this->belongsToMany(Lead::class, 'lead_allocations', 'lead_id', 'user_id')->where('active', true);
    }

    public function getFullNameAttribute()
    {
        return $this->first_name.' '.$this->last_name;
    }
    
}

solartherm-crm with vue.js/app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Models\Sap;
use PDF;
use Auth;
use Config;
use Validator;
use Setting;
use Illuminate\Validation\Rule;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Order;
use App\Models\OrderFinance;

class OrderController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $user = Auth::user();

        $orders = Order::paginate(15);
        $users = User::all();

        return view('orders.list', compact('orders', 'users'));
    }

    public function add(Request $request)
    {
        $sap = Sap::findOrFail($request->input('sap_id'));
        $order = Order::create(['lead_id' => $sap->lead->id, 'sap_id'=>$sap->id, 'status'=>'new']);

        return $order;
    }


    public function show(Order $order)
    {
        if(!$order->finance_completed_at) return redirect(url('orders/'.$order->id.'/finance'));
        return view('orders.show', compact('order'));
    }

    public function pdf(Request $request, Order $order)
    {
        $print = true;
        $filename = 'Order_'.$order->id.'.pdf';

        $pdf = PDF::loadView('orders.show', compact('order', 'print'));

        if($request->input('debug')) return view('orders.show', compact('order', 'print'));
        if($request->input('download')) return $pdf->download($filename);

        return $pdf->inline($filename);
    }

    public function finance(Request $request, Order $order)
    {
        $finance_q = OrderFinance::where('order_id', $order->id);
        $finance = $finance_q->first();

        if ($request->isMethod('POST')) {
            $rules = [
                'deposit' => 'required',
                'payment_method' => 'required|in:cash,finance'
            ];

            if($request->input('payment_method') == 'finance') {
                $rules = array_merge($rules, [
                    'finance.finance_lender' => ['required', Rule::in(array_column(Setting::get('lenders'), 'name'))],
                    'finance.finance_period' => 'numeric',
                    'finance.finance_rate' => 'numeric',
                    'finance.title' => ['required', Rule::in(Config::get('crm.english_honorifics')) ],
                    'finance.first_name' => 'required|max:100',
                    'finance.last_name' => 'required|max:100',
                    'finance.gender' => 'required|in:m,f,o',
                    'finance.dob' => 'required|date',
                    'finance.maiden_name' => 'required|max:100',
                    'finance.marital_status' => 'required|max:100',
                    'finance.nationality' => ['required', Rule::in(array_keys(Setting::get('countries')))],
                    'finance.dependants' => 'required|numeric',
                    'finance.landline_phone' => 'max:15',
                    'finance.mobile_phone' => 'max:15',
                    'finance.email' => 'required|email|max:255',
                    'finance.time_at_address' => 'required|numeric',
                    'finance.house_name' => 'required|max:100',
                    'finance.street' => 'required|max:100',
                    'finance.town' => 'required|max:65',
                    'finance.county' => ['required', Rule::in(array_keys(Setting::get('counties')))],
                    'finance.postcode' => 'required|max:8',
                    'finance.property_value' => 'numeric|min:0',
                    'finance.employment_status' => Rule::in(array_keys(Config::get('crm.employment_statuses'))),
                    'finance.annual_gross_income' => 'numeric|min:0',
                    'finance.current_debts' => 'numeric|min:0',
                    'finance.outstanding_mortgage' => 'numeric|min:0',
                    'finance.monthly_mortgage' => 'numeric|min:0',
                    'finance.previous_addresses' => 'nullable',
                    'finance.previous_addresses_time' => 'nullable|numeric',
                    'finance.bank_name' => 'required|min:3|max:255',
                    'finance.account_number' => 'required|numeric',
                    'finance.sort_code' => 'required|numeric',
                    'finance.time_with_bank' => 'required|numeric|min:0',
                    'finance.loan_amount' => 'required|numeric|min:0',
                    'finance.notes' => 'nullable'
                ]);
            }

            $validator = Validator::make($request->all(), $rules);

            if ($validator->fails()) return ["errors" => $validator->errors()];

            if($request->input('payment_method') == 'finance') {
                $req_data = $request->input('finance');
                $req_data['order_id'] = $order->id;

                if (!$finance) return OrderFinance::create($req_data);
                $finance_q->update($request->input('finance'));
            }

            $order->payment_method = $request->input('payment_method');
            $order->deposit = $request->input('deposit');

            if(!$order->finance_completed_at)
                $order->finance_completed_at = date('Y-m-d H:i:s');

            $order->save();
            return ["success" => true];
        }

        $customer = $order->sap->property;
        return view('orders.finance', compact('order', 'finance', 'customer'));
    }
    public function confirmation(Order $order)
    {
        return view('orders.signature', compact('order'));
    }

    public function sign(Request $request, Order $order)
    {
        $sig_data = [];

        if($request->input('customer_signature'))
        {
            $sig_data = [
                'customer_signature' => $request->input('customer_signature'),
                'customer_signed_ip' => $request->ip(),
                'customer_signed_at' => date("Y-m-d H:i:s"),
            ];

            $order->update($sig_data);
        }

        if($request->input('assessor_signature'))
        {
            $sig_data = [
                'assessor_signature' => $request->input('assessor_signature'),
                'assessor_signed_ip' => $request->ip(),
                'assessor_signed_at' => date("Y-m-d H:i:s"),
            ];

            $order->update($sig_data);
        }

        return $sig_data;
    }
}

solartherm-crm with vue.js/resources/views/orders/_bottom_bar.blade.php
<div class="card">
    <div class="card-block">
        <button class="btn btn-danger">Cancel</button>
        <button class="btn btn-primary pull-right" v-on:click="nextPage" id="submitButton">Next
        </button>
    </div>
</div>

solartherm-crm with vue.js/resources/views/orders/list.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-lg-3">
            @include('components.customer_search')
        </div>

        <div class="col-lg-9">
            <div class="card">
                <div class="card-header">
                    Orders
                </div>
                <div class="card-block">
                    <table class="table table-bordered table-striped table-condensed">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Postcode</th>
                            <th>Status</th>
                            <th>Date added</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($orders as $order)
                            <tr>
                                <td>{{$order->sap->property->first_name}}</td>
                                <td>{{$order->sap->property->postcode}}</td>
                                <td>{{$order->status}}</td>
                                <td>{{$order->created_at}}</td>
                                <td>
                                    <a href="{{ url('/orders/'.$order->id) }}" class="btn btn-primary">View</a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <nav>
                        {{ $orders->links('vendor.pagination.bootstrap-4') }}
                    </nav>
                </div>
            </div>
        </div>
        <!--/.col-->
    </div>
@endsection

solartherm-crm with vue.js/resources/views/orders/show.blade.php
<?php if (!isset($print)) $print = false; ?>

@extends($print ? 'layouts.print':'layouts.main')

@section('content')
    <div class="card">
        <div class="card-header">
            Goods &amp; Services
        </div>

        <div class="card-block">
            <div class="row">
                <div class="col-md-12">
                    <table class="table">
                        <tr>
                            <th>Good</th>
                            <th style="width: 90px;">Quantity</th>
                        </tr>
                        @foreach($order->sap->system->products as $product)
                            <tr>
                                <td>{{$product[0]}}</td>
                                <td>{{$product[1]}}</td>
                            </tr>
                        @endforeach
                    </table>

                    <table class="table">
                        <tr>
                            <th>Service</th>
                            <th style="width: 90px;">Included</th>
                        </tr>
                        @foreach($order->sap->system->services as $service)
                            <tr>
                                <td>{{$service}}</td>
                                <td>Yes</td>
                            </tr>
                        @endforeach
                    </table>

                    @if($order->notes)
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Additional Information/Equipment</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>{{$order->notes}}</td>
                            </tr>
                            </tbody>
                        </table>
                    @endif

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Energy Provider:</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td><h5>{{Setting::get('energy_providers')[$order->sap->property->energy_provider]}}</h5>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="row pure-g">
                <div class="col-md-6 pure-u-1-2">
                    <p>Please note:</p>

                    <ol>
                        <li>If you request changes that incur us additional time or cost, or if unforseen additional
                            works are required, we will provide you with a revised quote. Any additional charges will be
                            based on the installers hour rate of £30.00 + VAT
                        </li>
                        <li>We enclose a copy of terms of business/contract with this quote. Please read this
                            carefully.
                        </li>
                    </ol>

                    <p>*Please see the accompanied 'Solar PV Performance Estimate' AC Output document number
                        referenced.</p>
                </div>

                <div class="col-md-6 pure-u-1-2">
                    <table class="table">
                        <tbody>
                        <tr>
                            <td>Basic MCS Sap Calculation</td>
                            <td>@{{mcs_sap_calc}}</td>
                        </tr>
                        <tr>
                            <td>Estimated Performance *</td>
                            <td>@{{estimated_performance}}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header">Planning Permission</div>
        <div class="card-block">In most cases installing solar panels is likely to be considered "permitted development"
            however if the property is in a conservation area, the solar panels are to be ground mounted or protude
            above 200mm from the roof you will need to apply for planning permission, which may incur additional costs.
        </div>
    </div>

    <div class="card">
        <div class="card-header">Sub-contracting Installation Works</div>
        <div class="card-block">We may subcontract our some of the works, such as Scaffolding, EPC, etc. In accordance
            with the Microgeneration Certification Scheme we are responsible for ensuring that all sub-contracted works
            are carried out to standards required by MCS.
        </div>
    </div>

    <div class="card">
        <div class="card-header">Predicted Installation Date</div>
        <div class="card-block">
            We expect your solar installation to be completed no later than 3 weeks from the date of
            signing this contract.
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            Contract Order Form
        </div>

        <div class="card-block">
            <div class="row pure-g">
                <div class="col-sm-4 pure-u-1-3">
                    <dl>
                        <dt>First name</dt>
                        <dd>{{$order->sap->property->first_name}}</dd>

                        <dt>Last name</dt>
                        <dd>{{$order->sap->property->last_name}}</dd>
                    </dl>
                </div>
                <div class="col-sm-4 pure-u-1-3">
                    <dl>
                        <dt>Address</dt>
                        <dd>{{$order->sap->property->address_1}}<br/>
                            {{$order->sap->property->address_2}}<br/>
                            {{$order->sap->property->address_3}}
                        </dd>

                        <dt>Town</dt>
                        <dd>{{$order->sap->property->town}}</dd>

                        <dt>Postcode</dt>
                        <dd>{{$order->sap->property->postcode}}</dd>
                    </dl>
                </div>
                <div class="col-sm-4 pure-u-1-3">
                    <dl>
                        <dt>Email</dt>
                        <dd>{{$order->sap->property->email}}</dd>

                        <dt>Home Number</dt>
                        <dd>{{$order->sap->property->landline_phone}}</dd>

                        <dt>Mobile Number</dt>
                        <dd>{{$order->sap->property->mobile_phone}}</dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            Confirmation
        </div>

        <div class="card-block">
            <div class="row pure-g">
                <div class="col-md-6 pure-u-1-2">
                    <p>To accept the quotation please sign and return this form to Solartherm UK.</p>

                    <p>I agree to the quotation and confirm the order for the products and installation services
                        specified. I agree to the total cost and payment terms. I have read and agree to abide by
                        Solartherm UK Terms &amp; Conditions (Part 3) provided with the quotation/contract.</p>

                    <p>I understand any deposit paid is protected by the HIES insurance policy. A full copy of the
                        insurance policy can be obtained from the www.hies.org website.</p>
                </div>

                <div class="col-md-6 pure-u-1-2">
                    <table class="table table-striped">
                        <tbody>
                        <tr>
                            <td>
                                Total Order Price<br>
                                (inc VAT)
                            </td>
                            <td>£{{number_format($order->sap->system->system_cost, 2)}}</td>
                        </tr>
                        <tr>
                            <td>
                                Deposit<br>
                                (inc VAT)
                            </td>
                            <td>£{{number_format($order->deposit)}}</td>
                        </tr>
                        <tr>
                            <td>Method of Payment</td>
                            <td>{{Config::get('crm.payment_methods.'.$order->payment_method)}}</td>
                        </tr>
                        </tbody>
                    </table>

                    <p>Silvercrest Energy Limited trading as Solartherm, authorised and regulated by the Financial
                        Conduct Authority. We are a Credit Broker and not a Lender. We offer credit facilities from a
                        panel of lenders.</p>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('custom_styles')
    <style>
        body {
            background: inherit
        }

        .card {
            page-break-inside: avoid !important;
        }
    </style>
@endsection